spring.application.name=facens
spring.datasource.url=jdbc:mysql://localhost:3306/academica
spring.datasource.username=appuser
spring.datasource.password=SenhaForte@App123
spring.jpa.hibernate.ddl-auto=update